#!/bin/bash
echo "this script is from github"
NUMBER=$(($NUMBERONE + $NUMBERTWO))
echo "$NUMBER"
echo "HELLO ALL"
echo "Hai"
echo "this was run automagically"
echo "branch123"
echo "hotfixv0.1"
echo "feature2.0"
echo "feature3.0"
echo "hotfixv2.0.1"
echo "feature4.0"
echo "feature5.0"
echo "hotfix5.1"
echo "feature 6.0"
